[build]
  command = "npm run build"
  publish = "dist/test/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NETLIFY_SKIP_ANGULAR_RUNTIME = "true"
  NODE_VERSION = "20"
